version: "3.8"
services:
  app:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: ./build/Dockerfile.dev
    container_name: app
    env_file:
      - .env.example
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
